

export default function Page2(props){
  console.log(props)
  return <div style={{
    color:'#fff',
    border:'1px solid black',
    backgroundColor:'#008c8c'
  }}>
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minus amet dolor beatae magnam tempora, modi tempore, a architecto placeat quo, enim libero accusamus iure rerum expedita eligendi esse aliquam. Illum.
    Provident dignissimos illo earum, voluptatem quaerat in veniam voluptate. Deserunt nobis quibusdam dolorum voluptatum ad corrupti odio quasi maiores, reiciendis aliquam totam pariatur libero quam dolorem ea fuga voluptate fugiat!
    Quaerat odit maiores enim debitis aut cum alias ea saepe dolore culpa! Porro, a impedit. Accusantium facere, enim aliquam amet id minus doloribus explicabo quod iure ipsa incidunt, sunt blanditiis!
    Corrupti eligendi quod ab dolorum repudiandae aliquam enim iste praesentium. Reiciendis quidem dignissimos, incidunt explicabo, facere, praesentium nobis odio debitis magnam necessitatibus voluptas officiis qui. Similique dolorem pariatur suscipit dolor?
    Mollitia inventore excepturi animi amet hic illo eligendi ea iure eius nobis at quaerat, ad quos, dignissimos culpa corporis facilis suscipit odit expedita? Quod ratione, eum pariatur voluptatem commodi praesentium.
    Sint dolorum eaque mollitia! Numquam assumenda pariatur inventore impedit. Nulla eligendi pariatur perspiciatis expedita illo consequuntur repudiandae debitis adipisci, hic quae iusto repellat commodi maiores impedit quo officia dolorum deserunt?
    Et laudantium ut aliquam quasi minus omnis pariatur temporibus alias nemo, aliquid obcaecati harum eligendi quisquam error iure tenetur suscipit dicta iste similique exercitationem nihil excepturi recusandae molestias beatae! Sint.
    Atque natus, accusantium saepe sed rerum nisi minima sit minus error facere hic fugit exercitationem temporibus velit illo totam quasi sequi et tempora, ad soluta. Tempora consequuntur totam repellat similique!
    Dolores similique impedit, a ducimus ratione animi doloremque dolor nisi alias temporibus, earum ex magnam aut culpa accusamus nam, totam architecto iste! Consectetur, incidunt. Impedit quaerat consequuntur maiores accusantium voluptatem!
    Porro assumenda ullam reprehenderit debitis tempore molestias qui, vero quo aliquid, perspiciatis consequuntur soluta voluptate facere velit. Rem asperiores illum minus ex facilis odit dolorem quam vero eos, illo tempore!
    Deleniti quae, itaque porro blanditiis ipsa maiores voluptas consequatur non quos molestiae minima facilis eum harum sequi possimus sed laboriosam fuga atque sapiente error. At veniam nostrum labore in assumenda!
    Hic culpa voluptatem dolorem vel a eligendi perspiciatis officiis nemo quasi fuga quae harum ad praesentium commodi minima perferendis ipsa beatae id, voluptas, dignissimos provident repellendus! Dolorem temporibus qui ducimus?
    Id repudiandae cumque deleniti at error perspiciatis saepe vitae pariatur reprehenderit, illo dignissimos, neque voluptates accusantium rem, cum nam facere blanditiis esse nisi ab obcaecati aperiam perferendis eaque! Dolorem, necessitatibus?
    Error, quae neque harum doloremque dolore tempora voluptatem reiciendis ipsa! Totam, illo soluta voluptate quis, in, minus autem iste ut maiores reprehenderit rem tempore. Quia enim nulla blanditiis aspernatur molestias!
    Non error corrupti dolore dolorem aliquid iste quasi ullam, pariatur ducimus labore, blanditiis doloribus accusamus culpa. Velit iste doloremque voluptates quisquam autem exercitationem officiis, optio vel ullam. At, magni dolores?
    Soluta quisquam voluptas nihil dicta magni autem ab eligendi unde debitis quaerat aperiam, dolore, ad sequi id tenetur odio voluptatibus. Accusantium dolorem, cupiditate fugiat sed dolore voluptatum voluptas quo deserunt.
    Ducimus consequatur molestiae vero recusandae rerum ipsa. Dignissimos mollitia deleniti aliquid magni sit deserunt veritatis, itaque autem dolorem officiis, corrupti laboriosam similique cupiditate inventore asperiores. Commodi, eligendi consectetur. Nam, rerum.
    Eius praesentium facere et laborum suscipit rerum, fuga reprehenderit nisi repellat odit blanditiis cupiditate consectetur, eligendi veniam expedita. Error nemo nam ratione ab explicabo dolores quia corrupti placeat dolor ipsa?
    Nobis nisi non consequatur perspiciatis praesentium incidunt beatae deserunt ducimus eveniet velit alias quas, laudantium quaerat tempore possimus? Earum neque officiis beatae animi rem omnis atque odit quod, ipsam aliquid.
    Adipisci officia facere ipsa, maxime harum eligendi nam iusto eaque magni, eum non nisi? Temporibus, quidem eum dolor ad recusandae nihil tenetur numquam, ea rem inventore adipisci, minus et fuga?
    Obcaecati maxime tempore vel temporibus eum asperiores explicabo aspernatur fugiat sit, esse eveniet maiores dicta. Itaque aliquid, quam iusto officiis laboriosam quia nesciunt. Dolore minus, sunt numquam vel inventore neque.
    Dolorum, delectus ad cumque eveniet, non ipsum libero nihil modi, cupiditate illum id beatae quam perferendis placeat ullam voluptas repellat tempora sequi! Facere veniam magni ullam, qui vel corporis ipsam.
    Accusantium, ratione? Accusamus expedita dolorum vel aut officia, facere repellendus placeat possimus quibusdam nam. Qui voluptatum in ipsam magni earum ratione minima quia accusantium nam. Repudiandae laborum voluptatum eos aut!
    Rem possimus illum corporis aliquid ad itaque sint eos accusantium id eum, velit similique. Maiores ratione dolorum placeat incidunt corporis architecto iure odit? Repudiandae modi vitae tempore! Excepturi, esse ut.
    Libero labore ad sapiente quo, consectetur aspernatur cumque placeat quam similique rem voluptatibus, reiciendis debitis hic expedita! Quod distinctio nobis laborum odio sapiente itaque totam iure aut, perspiciatis dolores autem.
    Nulla, odio itaque beatae, natus eius veritatis ipsum officiis est expedita dolore ab, eligendi deleniti. Ducimus pariatur molestiae quam consequuntur ab quisquam. Delectus numquam, tempore corporis illo illum nam in!
    Modi tenetur dolor, deleniti rem amet libero aut culpa, nobis dolore vero dolorum suscipit pariatur, possimus facere! Reiciendis eum, veniam repudiandae non architecto fuga rem eveniet maiores in aut vero?
    Hic tempore cumque veritatis adipisci obcaecati minus dignissimos commodi numquam odit veniam distinctio mollitia voluptatem, ad similique beatae rerum illum! Architecto, porro aspernatur? Aperiam dignissimos accusantium ipsam culpa corrupti ipsum!
    Aliquid, molestiae beatae quo, adipisci, ratione reiciendis provident ea corrupti sed labore asperiores rerum sapiente. Repellat minus veniam quo quis, omnis numquam voluptatem quisquam magni doloribus ex amet est odio.
    Ducimus mollitia quisquam deleniti dolorem sint, natus culpa, nobis atque quae reprehenderit provident fugit est dolores corrupti, iste repellendus recusandae at ipsum hic maiores qui quos tempore? Odio, delectus aut.
    Temporibus aspernatur aut sit quis ab consequatur placeat, suscipit reprehenderit vero, sed, ipsa autem nostrum harum quod eum fugit sapiente beatae? Sapiente tenetur natus sint cumque est cum tempora atque.
    Pariatur nisi impedit voluptates molestiae nulla sit aliquam, labore obcaecati quisquam quaerat enim blanditiis rem ad facere. Ut, adipisci atque et quidem, rem ipsum, laboriosam itaque veritatis dolorem nisi sint.
    Quae aliquam commodi earum eum est atque quam. Architecto labore, iure odit ut possimus iste! Velit aliquid corrupti adipisci doloremque dolorem sed eligendi totam vel nesciunt, at, neque nostrum vitae!
    Sequi, ratione dolores officia excepturi eos dolorum est. Rerum, culpa modi consequuntur possimus similique, voluptatum magni veritatis molestiae saepe laboriosam incidunt dolor et, in quaerat aspernatur nobis! Nemo, porro rem?
    Ipsa eius molestias, voluptate aliquam reiciendis cupiditate commodi sit facilis magnam iusto quis deleniti esse rerum iste veniam vel rem perspiciatis porro? Nihil quas veniam quaerat delectus velit nostrum et!
    Autem architecto nostrum facilis laborum nihil eaque amet velit, quibusdam at magni maiores temporibus nesciunt ut aspernatur itaque dolorem! Officiis nulla magnam voluptatum eligendi ipsa vel quaerat tenetur ab corrupti?
    Consectetur, nobis. Ad quaerat corrupti, quidem similique cumque placeat sit debitis? Eum officiis obcaecati mollitia assumenda sint veniam aut incidunt, est reprehenderit qui minima, ducimus eius necessitatibus omnis! Magni, voluptates.
    Reiciendis ad facilis odit sint ipsum non eos in esse! Velit natus, numquam facere rerum architecto quis fugit aut exercitationem tempora asperiores totam ipsam alias, at consequuntur minus qui saepe.
    Molestiae, deleniti excepturi, ut veniam placeat pariatur voluptatem ea est inventore, sequi nesciunt quam illo quaerat fugiat perferendis. Quia cum optio molestias totam deleniti tempora ea, error ipsam odit blanditiis!
    Quae dolor rem ad dolorem inventore, autem assumenda id explicabo consectetur voluptas dolorum soluta odit quis. Tempore id cumque officia quos doloribus eos consequatur nisi est saepe et, dicta veniam?
    Dolor suscipit cupiditate, blanditiis quasi non sint quam nulla, quos nemo itaque aspernatur iure hic dicta perferendis iusto sunt ipsum, unde excepturi ullam. Optio enim possimus esse, explicabo dolorum laboriosam?
    Officia ipsam similique culpa nesciunt id et, qui dignissimos cum doloribus harum est quaerat exercitationem eaque natus, dolorum sequi. Sequi ipsam provident dolorum vero iste quaerat placeat, quisquam cumque magnam!
    Animi facilis sapiente asperiores debitis tempora. Minima deleniti magni, voluptate natus consequatur quibusdam, voluptates inventore ipsam pariatur aperiam perspiciatis consequuntur doloribus? Soluta dicta quo sapiente iure porro praesentium recusandae voluptates!
    Magnam nostrum placeat officiis et soluta iure est sapiente mollitia itaque accusamus, maxime, amet labore reiciendis esse voluptas unde expedita eos. Tempora ut, iusto expedita sunt nulla reprehenderit inventore ullam!
    Amet corporis perferendis exercitationem voluptas, assumenda ea odit aspernatur officiis veritatis aut doloremque quae, ipsum nihil nobis quod nulla dolores dicta beatae tempore dignissimos? Placeat accusantium similique voluptate sit tempora.
    Magni, ea libero eaque sunt fuga fugit quo tempora molestiae explicabo veritatis quis quisquam, a numquam ipsam officiis magnam tempore eveniet debitis rerum sint quia nulla qui dolorum! Harum, culpa.
    Deleniti minima ducimus ratione corporis nisi. Possimus, ipsam repudiandae expedita vitae sint velit tempore earum aspernatur suscipit id excepturi facilis nisi cupiditate ea ratione doloremque ipsum voluptate et sit. Officia.
    Nobis, consequuntur? Fugiat ipsa in molestias eaque atque, voluptatum, quas neque, sit nihil fugit saepe aliquid laudantium harum sequi ea delectus veritatis excepturi expedita non. Blanditiis excepturi reprehenderit eveniet atque!
    Est, excepturi doloribus! Nam et asperiores quasi libero quidem vero sed, obcaecati doloremque sequi. Alias quo aliquam iusto nulla temporibus eum accusantium voluptates ad rem dolorum, illo mollitia aperiam itaque.
    Nihil id natus, ad consequuntur ex nam! Distinctio excepturi harum iste? Ad aut, eum impedit nulla esse magni quia nam quo iste dolores mollitia incidunt voluptatum similique libero. Quam, voluptatem.
    Iste atque laboriosam exercitationem totam quas ad corporis possimus cumque. Reprehenderit delectus sapiente minima consequuntur suscipit. Harum rem ut ipsum expedita? Fuga error quisquam odit dolore quaerat perspiciatis officia nulla.
    Animi distinctio vitae, fuga vel voluptatum a quam aut, cumque dolorum, optio nemo eligendi minus quas saepe? Corporis nesciunt laborum saepe sed aliquam commodi, tenetur perferendis aliquid ullam placeat expedita.
    Illum ex ratione modi! Obcaecati eius repellat earum similique vero voluptatum ipsum ut soluta, laudantium nobis ratione nemo fuga esse maxime, non ullam reprehenderit. Animi adipisci repudiandae id dolorem illum.
    Commodi non consectetur sit fuga repellat dolores inventore quis at alias. Veritatis consequatur perspiciatis nobis temporibus fugit aperiam sunt, reiciendis quis hic quas iure doloribus. Magnam distinctio asperiores explicabo id.
    Consectetur possimus illo commodi debitis obcaecati repellat modi quae! Doloribus, voluptatem nisi nemo in consequuntur iure nulla. Neque, mollitia placeat quaerat dolorum, iusto odit vel suscipit delectus veniam, maxime minus.
    Quasi, aspernatur harum. Quod rerum tempora id voluptas? Dolores incidunt eligendi iure numquam, beatae odio. Unde, eligendi sit. Aut dicta in earum inventore nisi at, delectus fugiat sapiente adipisci distinctio!
    Dolorem ipsam quas natus vitae hic dignissimos, molestiae ex omnis delectus, maiores tenetur, a nesciunt nostrum distinctio facilis exercitationem blanditiis accusamus. Quidem impedit veritatis aperiam? Magni voluptates eligendi quo beatae!
    Maiores commodi dicta dolorem vitae voluptates aliquid quo illo vero quas veniam reiciendis dignissimos reprehenderit, veritatis itaque optio. Ipsa fuga dolores laborum dolor consequuntur, dicta libero voluptates. Expedita, porro labore?
    Possimus quisquam, doloribus animi tempore quis repudiandae, quia corrupti eligendi, rerum error iusto consequatur at ratione numquam sed neque illo repellendus ipsa libero temporibus. Nesciunt hic quo libero sapiente? Enim?
    Praesentium, ex natus consequatur nam hic labore dignissimos, blanditiis, ipsam accusantium minima nisi ea! Eaque, voluptate? Maiores minima, et at dolor doloremque sequi assumenda impedit provident beatae, corrupti aut inventore!
    Rem, saepe ea totam tenetur maxime est nulla voluptatibus doloribus molestiae nostrum nemo ex non dignissimos. Harum delectus sunt numquam dolorum maxime neque nobis quidem illo, amet, saepe veniam voluptatibus.
    Suscipit numquam in reiciendis! Provident id iusto labore autem similique, praesentium, voluptatibus cum quae doloremque sapiente perferendis repellendus ipsum harum fugiat tenetur libero non dolores quo eligendi adipisci excepturi quod?
    Cupiditate illo soluta ad eos, est vero dolores magnam. Obcaecati nostrum, necessitatibus eum quibusdam, vel debitis libero labore omnis facere qui quam, hic quia sed sit? Amet nostrum maxime esse.
    Harum assumenda enim ipsa hic non officiis soluta dolores libero, quis maiores, amet odit eum error expedita quo nulla? Laborum nihil, deleniti cumque ab ad optio. Ab provident dolorem commodi!
    Vitae id omnis fugiat ea pariatur repudiandae laudantium officiis sunt sed nihil impedit voluptatem dicta eos temporibus, dolor minus illum ut. Natus, vero asperiores corporis eligendi voluptas culpa quaerat nisi?
    Molestiae magni numquam nihil amet obcaecati voluptatem eaque dicta provident eligendi? Voluptates alias accusamus, nam magnam aliquam natus ea deserunt doloribus adipisci quaerat, quidem delectus facere nisi placeat dicta deleniti.
    Et labore, veniam mollitia eius dolorem, doloremque, numquam magni nobis incidunt maiores repellendus sit laudantium architecto ad aspernatur? Provident cupiditate aliquam unde ratione exercitationem, sequi ipsa voluptatem laboriosam earum inventore.
    Aut dignissimos earum doloribus ab voluptatum magni fugiat sed quasi veritatis odio officia neque iure labore deserunt, error dolore corporis animi placeat. Aspernatur incidunt officiis consectetur at explicabo consequatur. Consectetur.
    Iure maxime porro ipsam, nihil qui molestias animi ratione atque doloremque dicta explicabo voluptates consequuntur quae dolores quod, sint, recusandae numquam. Libero molestias minima quam consequuntur, aliquid error voluptatum eligendi!
    Libero voluptate harum illo explicabo beatae deserunt a quasi optio perferendis modi corporis earum iusto, eum officia! Nam vitae praesentium sapiente, nobis sint, cum consectetur autem dignissimos nihil id iste!
    Quibusdam, cupiditate fugiat. Qui voluptas ut quod tempore, debitis commodi ad quis dicta sequi vero totam iste doloremque, fuga tenetur sit repudiandae voluptatum temporibus in! Voluptas magni sunt odio repellat!
    Beatae, omnis! Maxime mollitia adipisci cupiditate maiores, doloremque libero optio assumenda quia reprehenderit quidem quod? Adipisci aperiam qui ducimus omnis et facilis, quibusdam optio, provident velit magni perferendis, eligendi ut!
    Natus nemo ex minima iste tempora beatae iusto repudiandae aperiam deleniti sunt molestiae aliquam enim, mollitia et odio a alias autem. Molestiae ratione debitis tempore tempora facere beatae corporis commodi.
    Maxime iure sed repellendus possimus quidem odio officia, omnis minima. Eveniet possimus corporis, nostrum, deleniti corrupti perspiciatis expedita recusandae fugiat consequatur dignissimos sapiente fugit quam eos provident placeat autem minima.
    Explicabo eaque excepturi, placeat nesciunt mollitia hic architecto quia provident voluptate at ducimus dolor culpa rem quis et fugiat ipsa! Quibusdam quis, porro illo officia odio sapiente. Dolores, repellendus quibusdam?
    Iusto voluptatem mollitia eius et perferendis quae placeat provident? Cumque vel necessitatibus accusantium at reprehenderit unde itaque expedita, tenetur facere asperiores nisi, corrupti saepe voluptatibus repudiandae error, consectetur nulla aperiam.
    Quae, veritatis? Tempora est sapiente maxime doloribus placeat dolorum quos deleniti reiciendis, incidunt omnis, alias magnam. Expedita corporis itaque atque deleniti consequatur, et, temporibus ratione ipsum omnis quae laborum nostrum.
    Praesentium perspiciatis consequuntur exercitationem unde expedita dicta officia ducimus quia. Harum id adipisci quisquam officia atque reprehenderit ut dolore? Qui, dolore quam. Molestias nisi esse enim? Illum repellendus vero laborum.
    Totam alias eius id obcaecati a, voluptate possimus, placeat, autem tenetur temporibus hic cum ipsa! Accusantium hic consequatur, praesentium placeat quas voluptatibus ipsum ad maxime facilis culpa, eos alias nihil.
    Eius, exercitationem. Placeat consectetur quo quaerat vero, ab impedit sunt molestias veniam nam! Sequi pariatur quidem deleniti ducimus molestias aliquam perspiciatis totam inventore ad mollitia! Debitis iure distinctio deserunt molestias.
    A reprehenderit ipsa, enim sunt quaerat, veritatis distinctio fugiat cum, explicabo qui dicta natus. Modi iste ad quod sequi consectetur ea dicta dignissimos numquam recusandae, debitis dolorem ducimus ex animi.
    Molestias facere consequuntur blanditiis velit, cupiditate optio dolorem, eaque tempora dolor voluptatem ratione perferendis asperiores. Cum odio vitae tenetur. Excepturi distinctio ratione commodi error harum officia explicabo, natus voluptatum exercitationem?
    Fugiat officiis similique non iure, dignissimos tempore rem totam. Nisi ipsa minus et odio cum ducimus amet cupiditate velit eius. Earum totam qui voluptatum, aliquam labore quibusdam veritatis nemo expedita.
    Quo nulla porro tempora quas saepe, pariatur sit, veniam quisquam quae animi delectus dolores iure ad vitae fugit dolor amet? Laborum consequuntur dolore sed eius blanditiis voluptatum modi, molestiae hic?
    Odit, nulla assumenda soluta doloribus voluptatem quas iusto repellendus, laborum autem eos fugit ab quia ratione, ullam eum provident? Dignissimos nemo aperiam, rem sint adipisci repellendus? Vel autem asperiores laudantium.
    Reiciendis vitae nihil beatae libero ipsa asperiores, ut quidem quae, tenetur quasi neque? Sequi impedit nobis quam culpa quae cupiditate voluptatum ea, eius, error nesciunt nisi laboriosam ipsum distinctio similique.
    Itaque dolore animi dolor, error aliquid quae ullam officiis est esse vero saepe id cumque omnis alias ut tempora perferendis, nemo atque? Ad reprehenderit eveniet exercitationem nemo voluptatum velit officiis?
    Reiciendis doloribus consectetur vel! Et sequi odio iste accusantium ducimus adipisci minus maxime, minima quam mollitia saepe, quidem incidunt harum dolore voluptatibus magni, hic dicta porro! Quia impedit harum asperiores.
    Cum magni enim voluptates, velit ducimus dolores iste sunt molestiae reprehenderit, aliquid fugiat, dolor eum veritatis assumenda blanditiis accusantium cupiditate. Facere ut reprehenderit incidunt veniam rerum, asperiores quis error non.
    Fugit debitis enim corrupti eius, voluptas dolorum iusto dicta consequuntur aspernatur quos vitae earum fugiat vel ab, porro deleniti nihil asperiores dignissimos doloribus. Neque, ratione. Voluptatem sapiente modi iure et.
    Veritatis iure soluta quasi praesentium eveniet, quibusdam quia dolor quae magni odio dolorem delectus corrupti dolore nam voluptatibus ipsam modi cum. Iusto culpa obcaecati modi fugit, nemo voluptatum asperiores quas?
    Sint dolorum sapiente fugit consectetur eligendi necessitatibus ducimus totam, praesentium beatae, illum, nisi fuga nostrum voluptates quo blanditiis quae eaque quas incidunt provident! Aut voluptatem, explicabo cumque ipsa voluptatum enim.
    Reprehenderit pariatur ipsum nostrum libero sit aut voluptates amet accusamus et quod fuga quia ut labore necessitatibus, commodi iste debitis vero nesciunt corporis quisquam dolore qui doloremque. Dolores, quod ipsum.
    Aliquam cupiditate cumque dolores recusandae exercitationem maxime accusantium aut doloribus ducimus? Dignissimos repudiandae magnam, exercitationem quisquam, suscipit illum, deleniti harum natus similique expedita rem eveniet recusandae blanditiis impedit incidunt dolorum!
    Totam recusandae magnam praesentium impedit architecto veritatis molestias perspiciatis quod quidem, aliquam non eius, quas soluta! Aperiam nobis fuga, tempore vitae voluptas impedit dolorum nisi placeat. Aliquid ipsa et expedita.
    Ducimus aliquam ea odio perspiciatis laboriosam delectus soluta minus, doloribus odit nisi a recusandae ut, ipsa, dolores ipsum? Porro alias rem perferendis quam nostrum soluta, culpa pariatur officia consectetur delectus!
    Praesentium ut, quis aut beatae, saepe deserunt rem, vitae deleniti consectetur in et debitis perspiciatis fugit. Esse consectetur cum aspernatur eligendi blanditiis quidem. Voluptate dolorem delectus vero possimus incidunt labore.
    Sed id alias vel quos et ea debitis tenetur labore aspernatur molestiae libero, provident explicabo praesentium dignissimos quo nam corporis aut quaerat minus, iusto ipsa est facilis dicta accusantium. Beatae.
    Maxime consectetur dolore dicta odio harum quaerat debitis vitae ipsa, nulla voluptas, quibusdam sit eum impedit corporis natus praesentium, non unde possimus nisi modi voluptates repellat nihil quam. Eius, id?
    Omnis, perspiciatis harum incidunt cupiditate assumenda nobis hic unde, soluta iusto, fugiat voluptatibus itaque numquam. Maxime, possimus, fuga vel et sapiente dignissimos eius iure nisi delectus rerum omnis, ut quis?
  </div>
}